# Generated by Django 3.0.5 on 2020-11-03 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rx_patient_name', models.CharField(max_length=255)),
                ('rx_address', models.CharField(max_length=255)),
                ('rx_description', models.CharField(max_length=1000)),
                ('rx_refill', models.CharField(choices=[('1 Month', '1 Month'), ('3 Month', '3 Month'), ('6 Month', '6 Month'), ('8 Month', '8 Month'), ('12 Month', '12 Month')], default='1 Month', max_length=20)),
                ('rx_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
