# Generated by Django 3.0.5 on 2020-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='rx_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
