# Generated by Django 3.0.5 on 2020-11-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_prescriptions_rx_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='rx_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2500),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='rx_drug',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
