# Generated by Django 3.0.5 on 2020-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(default='SchoolProject', max_length=255),
        ),
    ]
